before_script:
  - /opt/rh/rh-python36/root/usr/bin/pip3.8 install virtualenv
  - virtualenv -p /opt/rh/rh-python38/root/usr/bin/python3.8 venv
  - ./venv/bin/pip install --upgrade pip
  - ./venv/bin/pip install -r requirements.txt


stages:
  - test

test:
  stage: test
  script:
    - ./venv/bin/python -m unittest discover -s tests -p *test.py
